### ISSUE TITLE
쇼핑몰 리스트 가져오기 API 개발

### ISSUE THREAD

**Issue by labyu** [cocoding-ss/apjung-backend#102]
이후에 여러 정렬 조건을 통해 쇼핑몰 리스트를 가져올 예정이기 때문에 복잡한 쿼리가 예상됩니다.

- Response용 Dto가 필요합니다. Shop 도메인 객체를 1차원으로 만들어주세요. Thumbnail과 같은 경우는 publicUrl만 있으면 됩니다.
- QueryDSL을 사용해주세요.

정렬 조건은 다음 두가지입니다.
1. 최신순 (가장 최근에 만들어진 쇼핑몰)
2. 인기순 ( ViewStat 객체의 PV * 0.4 + UV * 0.6 ) - 기본
3. 쇼핑몰 이름 가나다순

**Comment by YoungWukJeon** [comment]
~검색어를 통한 쇼핑몰 이름으로 검색 기능 추가~

정렬과 페이징 작업을 먼저 진행하고 필터 조건은 이후에 작업하면 될 거 같아요.

**Comment by YoungWukJeon** [comment]
쇼핑몰 이름을 통해 검색하는 부분은 **like %name%** 로 작성
- 쇼핑몰 전체 리스트의 데이터는 많지 않고 데이터의 길이도 길지 않아서 풀스캔시 성능이 나쁘지 않을 것으로 예상됨.

**Comment by YoungWukJeon** [comment]
Querydsl 참고 Url
- https://jojoldu.tistory.com/372?category=637935
- https://joont92.github.io/jpa/QueryDSL/
- https://jojoldu.tistory.com/394
- https://ict-nroo.tistory.com/117
