### ISSUE TITLE
쇼핑몰 태그 기능 개발

### ISSUE THREAD

**Issue by labyu** [cocoding-ss/apjung-backend#105]
쇼핑몰에 붙이는 태그 기능이 필요함 이후에 Get API와 Search API에서도 Tag 리스트를 내려주어야한다.

### 추가 스키마

tags 테이블 -- extends SoftDeletableEntity
태그 키
태그 이름

shops_tags 테이블 -- extends SoftDeletableEntity
쇼핑몰 키
태그 키

### API 추가
PUT /shop/{id}/tags 쇼핑몰 번호로 태그 추가

### API 변경
쇼핑몰 생성, 변경 API에서 태그에 대해서 변경 필요
POST /shop
PUT /shop/{id}

**Comment by labyu** [comment]
이 태그에 브랜드를 포함한다

**Comment by YoungWukJeon** [comment]
쇼핑몰에 붙이는 태그 기능에 Search API에서도 Tag 리스트를 내려준다고 하셨는데, 나중에 쇼핑몰을 태그로 검색하는 기능도 추가되는 건가요?

**Comment by labyu** [comment]
태그 기능 개발 이후에 도입할 예정입니다. 우선은 쇼핑몰에 태그를 표시하는 정도로만 개발할 예정입니다.
