### ISSUE TITLE
UV PV 기능 개발

### ISSUE THREAD

**Issue by labyu** [cocoding-ss/apjung-backend#107]
DB의 UV, PV를 올리는 작업은 querydsl update문을 통해 해주어야한다. (Where shop_id={id})

### 로직
PV는 GET /shop/{id} API에 접근할 때마다 1씩 올려준다.
UV는 사용자가 위 API 에 접근했을 때 shops_view_logs에 접근한 사용자 번호화 쇼핑몰 번호, 그리고 당시 날짜의 로우가 없다면 shops_view_stats 테이블의 UV+1 있다면 shops_view_logs 테이블의 해당 로우의 count를 +1해준다.

### 스키마 변경
기존 shops 테이블에서 page_view, unique_view를 제거

-- shops_view_stats 테이블을 새로 생성한다 -- 아무것도 상속받지 않는다 (SoftDeletableEntity 상속 X)
쇼핑몰 키
page_view
unique_view

-- shops_view_logs 테이블을 생성한다 -- 아무것도 상속받지 않는다
기본키
쇼핑몰 키
사용자 키
일자 (DATE)
count

**Comment by YoungWukJeon** [comment]
> ### 로직
> PV는 GET /shop/{id} API에 접근할 때마다 1씩 올려준다.
> UV는 사용자가 위 API 에 접근했을 때 shops_view_logs에 접근한 사용자 번호화 쇼핑몰 번호, 그리고 당시 날짜의 로우가 없다면 shops_view_stats 테이블의 UV+1 있다면 shops_view_logs 테이블의 해당 로우의 count를 +1해준다.

@labyu 

위의 말의 시나리오가
1) 최초로 특정 사용자가 특정 쇼핑몰을 오늘 조회했다.
-> shops_view_logs에 특정 사용자, 특정 쇼핑몰, 오늘날짜에 해당하는 레코드가 없을테니 shops_view_stats 테이블에 특정 쇼핑몰에 해당하는 page_view와 unique_visitor를 1씩 증가 시키고, shops_view_logs 테이블에 새로운 레코드를 추가하고 count를 1로 만든다.

2) 같은 날 특정 사용자가 특정 쇼핑몰을 재조회했다.
-> shops_view_logs에 특정 사용자, 특정 쇼핑몰, 오늘날짜에 해당하는 레코드가 있을 것이니 shops_view_stats 테이블에 특정 쇼핑몰에 해당하는 page_view만 1 증가시키고, shops_view_logs 테이블의 해당 레코드의 count를 1 증가시킨다.

이렇게 이해하면 되는건가요?

**Comment by YoungWukJeon** [comment]
https://github.com/cocoding-ss/apjung-backend/tree/feature/issue%23107

스키마 변경하고 Entity 생성 했는데 시간 되시면 스키마 내용과 Entity 의존관계 확인 한 번 부탁드릴게요~~

**Comment by YoungWukJeon** [comment]
`GET /shop/{id}`로 요청을 보냈을 때, 결과로 pv와 uv도 같이 내려주나요?

**Comment by labyu** [comment]
> `GET /shop/{id}`로 요청을 보냈을 때, 결과로 pv와 uv도 같이 내려주나요?

UV PV는 굳이 사용자에게 보여지지 않아도 된다고 생각해서 넣지 않았습니다. `인기순`과 같은 정렬 로직, 추천로직에 사용될 예정입니다.

> > ### 로직
> > PV는 GET /shop/{id} API에 접근할 때마다 1씩 올려준다.
> > UV는 사용자가 위 API 에 접근했을 때 shops_view_logs에 접근한 사용자 번호화 쇼핑몰 번호, 그리고 당시 날짜의 로우가 없다면 shops_view_stats 테이블의 UV+1 있다면 shops_view_logs 테이블의 해당 로우의 count를 +1해준다.
> 
> @labyu
> 
> 위의 말의 시나리오가
> 
> 1. 최초로 특정 사용자가 특정 쇼핑몰을 오늘 조회했다.
>    -> shops_view_logs에 특정 사용자, 특정 쇼핑몰, 오늘날짜에 해당하는 레코드가 없을테니 shops_view_stats 테이블에 특정 쇼핑몰에 해당하는 page_view와 unique_visitor를 1씩 증가 시키고, shops_view_logs 테이블에 새로운 레코드를 추가하고 count를 1로 만든다.
> 2. 같은 날 특정 사용자가 특정 쇼핑몰을 재조회했다.
>    -> shops_view_logs에 특정 사용자, 특정 쇼핑몰, 오늘날짜에 해당하는 레코드가 있을 것이니 shops_view_stats 테이블에 특정 쇼핑몰에 해당하는 page_view만 1 증가시키고, shops_view_logs 테이블의 해당 레코드의 count를 1 증가시킨다.
> 
> 이렇게 이해하면 되는건가요?

넵 이해하신대로가 맞습니다. 이 때 `날짜`라는 데이터는 YY-MM-DD까지만 입력해주시고 사용자 컬럼과 함께 인덱스 걸어주시면 될 것 같습니다.

> https://github.com/cocoding-ss/apjung-backend/tree/feature/issue%23107
> 
> 스키마 변경하고 Entity 생성 했는데 시간 되시면 스키마 내용과 Entity 의존관계 확인 한 번 부탁드릴게요~~

https://github.com/cocoding-ss/apjung-backend/blob/feature/issue%23107/api/src/main/java/me/apjung/backend/domain/shop/ShopViewLog.java

여기 access_count = 1보다는 Hibernate의 Default Value(@PrePersist등)를 사용하시거나, 비즈니스 로직에서 초기값을 설정해주는 것이 좋은 것 같습니다.

https://github.com/cocoding-ss/apjung-backend/blob/feature/issue%23107/api/src/main/resources/db/migration/V20201211043925__Create_Shops_View_Logs_Table.sql

accessed_at과 accessed_count로 해주시는 것이 더 좋을 것 같습니다.

**Comment by YoungWukJeon** [comment]
> 넵 이해하신대로가 맞습니다. 이 때 `날짜`라는 데이터는 YY-MM-DD까지만 입력해주시고 사용자 컬럼과 함께 인덱스 걸어주시면 될 것 같습니다.

질문이 있습니다!

1. YYYY-MM-DD가 아니고 YY-MM-DD인가요?

2. user_id와 date에 대해 인덱스를 생성해달라고 하셨는데 그렇다면 shop_id도 같이 걸어야 하지 않을까요?

**Comment by labyu** [comment]
> > 넵 이해하신대로가 맞습니다. 이 때 `날짜`라는 데이터는 YY-MM-DD까지만 입력해주시고 사용자 컬럼과 함께 인덱스 걸어주시면 될 것 같습니다.
> 
> 질문이 있습니다!
> 
> 1. YYYY-MM-DD가 아니고 YY-MM-DD인가요?
> 2. user_id와 date에 대해 인덱스를 생성해달라고 하셨는데 그렇다면 shop_id도 같지 걸어야 하지 않을까요?

아하 YYYY-MM-DD가 맞습니다 ㅎㅎ. 아래 사항도 맞습니다.

**Comment by YoungWukJeon** [comment]
> 여기 access_count = 1보다는 Hibernate의 Column Default Value를 사용하시거나, 비즈니스 로직에서 초기값을 설정해주는 것이 좋은 것 같습니다.
> 
> https://github.com/cocoding-ss/apjung-backend/blob/feature/issue%23107/api/src/main/resources/db/migration/V20201211043925__Create_Shops_View_Logs_Table.sql
> 
> accessed_at과 accessed_count로 해주시는 것이 더 좋을 것 같습니다.

확인해보고 반영하겠습니다!
