### ISSUE TITLE
미작성된 테스트 코드 작업 및 MockMvc 테스트 다듬기

### ISSUE THREAD

**Issue by YoungWukJeon** [cocoding-ss/apjung-backend#111]
1. 현재 개발된 기능(auth, shop)들에 대해 서비스와 리포지터리 등의 미작성된 테스트 코드 작업
2. RestDocs 작성을 위한 테스트 코드 리팩토링
3. adoc 파일 수정 (request, response, error 등 포맷팅 작업이 필요해 보임)

참고 링크
- https://jaehun2841.github.io/2019/08/04/2019-08-04-spring-rest-docs/
- https://woowabros.github.io/experience/2020/05/13/rest-docs.html

**Comment by labyu** [comment]
요번 테스트 리팩토링에서 data.sql을 걷어내고 Mocking 테스트 할 때 `@BeforeEach`를 사용하려고 하는데 이유는 다음과 같습니다.

1. SQL 의존성을 벗어나기 위해
2. data.sql의 동작을 정확히 이해하기 어려움

카니님 의견 있으시면 부탁드립니다!

**Comment by YoungWukJeon** [comment]
> 요번 테스트 리팩토링에서 data.sql을 걷어내고 Mocking 테스트 할 때 `@BeforeEach`를 사용하려고 하는데 이유는 다음과 같습니다.
> 
> 1. SQL 의존성을 벗어나기 위해
> 2. data.sql의 동작을 정확히 이해하기 어려움
> 
> 카니님 의견 있으시면 부탁드립니다!

@ BeforeEach나 @BeforeAll을 통해 사용할 수도 있을 것 같지만 SQL 스키마 변경이나 여러 사항들에 대해 관리가 좀 힘들지 않을까요? abstract 테스트들을 만들어서 사용하면 중복코드는 줄어들 것 같긴한데, 뭔가 변경이 있을 때 data.sql 파일 하나 수정하면 되는데 클래스에 넣으면 테스트 코드의 수정이 많아질 것 같습니다.
