### ISSUE TITLE
쇼핑몰 검색 및 리스팅 기능 개선

### ISSUE THREAD

**Issue by labyu** [cocoding-ss/apjung-backend#119]
태그와 인증프로세스 추가로 다음과 같은 조건이 추가되었습니다.

1. 키워드 검색은 태그또한 함께 검색되어야합니다.
2. 노출되는 모든 쇼핑몰은 ShopSafeLevel.NORMAL 또는 ShopSafeLevel.SAFE 여야 합니다.

**Comment by YoungWukJeon** [comment]
@labyu 

검색 결과에 대해서 
```json
{
    "name_result": [
        ...
    ], "tag_result": [
        ...
    ]
}
```
이런 형식으로 내려주면 될까요?
그렇다면 검색 결과에 `name_result`의 결과랑 `tag_result`의 결과랑 중복된 `shop`이 존재할 수 있을텐데 
중복되더라도 그대로 내려주면 될까요?

**Comment by YoungWukJeon** [comment]
``GET /shop/search?filter.name=검색내용&...`` 이런식의 요청을 보낼때 `filter.name`의 내용을 가지고 **쇼핑몰 이름 검색**, **쇼핑몰 태그 검색**이 이루어지는데, 태그는 무조건 하나만 검색을 할 수 있는 것으로 이해하면 될까요?

**Comment by YoungWukJeon** [comment]
태그 검색도 이름 검색과 같이 **like %name%** 으로 처리하면 될까요?

**Comment by labyu** [comment]
태그 검색은 LIKE {KEYWORD}% (인덱스를 타기위함)  해주시면 됩니다. Response 형식은 기존 Response Dto를 이용합니다. JOIN과 GROUP BY를 사용하시면 태그검색과 이름검색을 동시에 하시더라도 기존 Response DTO에 매핑하실 수 있으실 것 같습니다.

**Comment by YoungWukJeon** [comment]
> Response 형식은 기존 Response Dto를 이용합니다. JOIN과 GROUP BY를 사용하시면 태그검색과 이름검색을 동시에 하시더라도 기존 Response DTO에 매핑하실 수 있으실 것 같습니다.

@labyu 

검색결과에서는 태그에 대한 검색결과와 쇼핑몰 이름에 대한 검색 결과를 구분할 필요가 없다는 말씀이신가요?

**Comment by labyu** [comment]
> 검색결과에서는 태그에 대한 검색결과와 쇼핑몰 이름에 대한 검색 결과를 구분할 필요가 없다는 말씀이신가요?

넵

**Comment by YoungWukJeon** [comment]
> > 검색결과에서는 태그에 대한 검색결과와 쇼핑몰 이름에 대한 검색 결과를 구분할 필요가 없다는 말씀이신가요?
> 
> 넵

확인했습니다!
