### ISSUE TITLE
검색 api 결과에 태그 추가

### ISSUE THREAD

**Issue by YoungWukJeon** [cocoding-ss/apjung-backend#128]
- 검색 결과에 태그 추가하기
- 현재 검색하는 Querydsl에서 가져온 shop에서 getShopTags() 해도 못가져오는 거 같으니 이부분 확인(Lazy 걸려있기는 함)

**Comment by labyu** [comment]
이 이슈에서 SearchAPI의 쿼리파라미터 Depth 줄이는 것도 함께 작업하겠습니다.
