### ISSUE TITLE
JWT 인증 개선

### ISSUE THREAD

**Issue by labyu** [cocoding-ss/apjung-backend#130]
현재 편의상 refresh_token을 구현하지 않았는데, refresh_token 구현이 필요합니다. refreshToken은 UserTable에 컬럼으로 추가해서 관리하면 될 것 같습니다.

1. 스키아 정의 필요
2. 로직 구현 필요

**Comment by labyu** [comment]
컬럼 이름

컬럼 이름 : refresh_token
변수이름 : refreshToken

컬럼 이름 : refresh_token_expired_at
변수 이름 : refreshTokenExpiredAt

rereshToeknExpiredAt이 너무 길다면 `@Embedded`를 통해 RefreshToken을 객체화한 후 변수 이름을  token, expiredAt 이렇게 설정해주셔도 됩니다 (컬럼 명은 변경 없음)

**Comment by YoungWukJeon** [comment]
jwt 방식의 token을 사용하기 때문에 expired_at은 필요없어 보입니다.

**Comment by YoungWukJeon** [comment]
access_token 재발급 api에서 요청 파라미터와 토큰(refresh_token)에 따라 별도의 예외처리

https://tools.ietf.org/html/rfc6749#section-5.2

https://developers.cafe24.com/app/front/develop/oauth/retoken
